name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run doctests
        env:
          JAX_PLATFORMS: cpu
          XLA_PYTHON_CLIENT_PREALLOCATE: 'false'
        run: |
          pytest -n auto src/bijx/ --doctest-modules

      - name: Run tests
        env:
          JAX_PLATFORMS: cpu
          XLA_PYTHON_CLIENT_PREALLOCATE: 'false'
        run: |
          pytest -n auto tests/ src/bijx/
